name: Mirror to GitFlic

on:
  push:
    branches: [master, main]
  delete:
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to GitFlic
        run: |
          git remote add gitflic https://${{ secrets.GITFLIC_USERNAME }}:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/project/mtt-klyueva/familymodel.git
          git push gitflic --all --force
          git push gitflic --tags --force
