name: Mirror to GitFlic

on: [push]

jobs:
  mirror-to-gitflic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to GitFlic
        run: |
          git remote add gitflic https://gitflic.ru/project/mtt-klyueva/familymodel.git
          git push --force --all gitflic
          git push --force --tags gitflic
